runtime: python27
api_version: 1
threadsafe: true
handlers:  
- url: /(.*\.(gif|png|jpg|svg|ico|css|js)(|\.map))$
  static_files: /\1
  upload: /(.*)(|\.map)
- url: /(.*)
  static_files: /index.html
  upload: /index.html