runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  static_files: dist/client/\1
  upload: dist/client/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/client/\1
  upload: dist/client/(.*\.html)

...

# Site root.
- url: /
  static_files: dist/client/index.html
  upload: dist/client/index.html

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/client/index.html
  upload: dist/client/index.html

skip_files:
- ^(?!dist)